name: Create PR for release

# checks the latest release on
# https://github.com/IBM/openapi-validator/releases. For the latest release, if
# no branch or tag exists locally for that release (e.g. "v0.19.0"), then a new
# branch is created and PR opened to bump the version.

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  latest-version:
    name: Check release, make PR
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Fetch all git history
      run: git fetch --prune --unshallow --tags

    - name: Get latest openapi-validator tag
      id: latest_tag
      uses: abatilo/release-info-action@v1.3.1
      with:
        owner: IBM
        repo: openapi-validator

    - name: Debug, show latest version
      run: |
        echo "latest_tag='${{ steps.latest_tag.outputs.latest_tag }}'"

    - name: Check for existing tag, update Dockerfile
      id: update_sh
      continue-on-error: true
      run: |
        ./update.sh ${{ steps.latest_tag.outputs.latest_tag }}

    - name: Debug, show update results
      run: |
          echo "found='${{ steps.update_sh.outputs.found }}'"
          echo "name='${{ steps.update_sh.outputs.name }}'"
          echo "make_pr='${{ steps.update_sh.outputs.make_pr }}'"

    - name: Create PR for new release
      if: steps.update_sh.outputs.make_pr == 'yes'
      uses: peter-evans/create-pull-request@v3.8.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Bump to ${{ steps.latest_tag.outputs.latest_tag }}"
        title: "Bump to ${{ steps.latest_tag.outputs.latest_tag }}"
        branch: "${{ steps.latest_tag.outputs.latest_tag }}"
